import 'dart:convert';

import 'package:http/http.dart' as http;

import '../../features/authentication/data/auth_http_client.dart';
import '../../features/authentication/data/auth_repository.dart';

/// An asset stored by the platform's media service.
///
/// The app never sees a storage credential. It posts the bytes to the API,
/// which signs the upload and files it under the tenant's own folder, and gets
/// back a URL it can render and persist.
class MediaAsset {
  const MediaAsset({
    required this.secureUrl,
    required this.publicId,
    required this.resourceType,
    required this.bytes,
  });

  factory MediaAsset.fromJson(Map<String, dynamic> json) => MediaAsset(
    secureUrl: json['secureUrl'] as String? ?? '',
    publicId: json['publicId'] as String? ?? '',
    resourceType: json['resourceType'] as String? ?? 'image',
    bytes: (json['bytes'] as num?)?.toInt() ?? 0,
  );

  final String secureUrl;
  final String publicId;
  final String resourceType;
  final int bytes;
}

/// Uploads one file per request to `POST /api/media/upload`.
///
/// The limits are the API's, restated here only so the app can fail before
/// spending a large upload on a request that will be refused.
class MediaRepository {
  MediaRepository({
    required String baseUrl,
    String? accessToken,
    AccessTokenProvider? accessTokenProvider,
    http.Client? client,
  }) : assert(
         accessToken != null || accessTokenProvider != null,
         'Provide an access token or token provider.',
       ),
       _baseUri = Uri.parse(baseUrl.trim().replaceAll(RegExp(r'/+$'), '')),
       _accessToken = accessToken,
       _accessTokenProvider = accessTokenProvider,
       _client = client ?? createAuthHttpClient();

  final Uri _baseUri;
  final String? _accessToken;
  final AccessTokenProvider? _accessTokenProvider;
  final http.Client _client;

  /// What the API accepts. Anything else is refused there, so it is refused
  /// here first rather than after the bytes have gone over the wire.
  static const maxBytes = 10 * 1024 * 1024;
  static const allowedExtensions = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'pdf'];

  Future<MediaAsset> upload({
    required List<int> bytes,
    required String fileName,
  }) async {
    if (bytes.isEmpty) {
      throw const MediaException('That file is empty.');
    }
    if (bytes.length > maxBytes) {
      throw const MediaException('Images and PDFs must not exceed 10 MB.');
    }

    final response = await _authorizedSend(
      (headers) async {
        final request = http.MultipartRequest(
          'POST',
          _baseUri.resolve('/api/media/upload'),
        )
          ..headers.addAll(headers)
          // The field has to be named `file`; the API skips every other field
          // and then reports that none was supplied.
          ..files.add(
            http.MultipartFile.fromBytes('file', bytes, filename: fileName),
          );
        return http.Response.fromStream(await _client.send(request));
      },
    );

    return MediaAsset.fromJson(_data(response));
  }

  /// Multipart boundaries are generated by the request, so no content-type is
  /// set here — supplying one makes the upload unparseable on the other side.
  Map<String, String> _headers(String token) => {
    'authorization': 'Bearer $token',
    'x-client-surface': 'app',
    'accept': 'application/json',
  };

  Future<http.Response> _authorizedSend(
    Future<http.Response> Function(Map<String, String> headers) send,
  ) async {
    var token = await _resolveAccessToken();
    var response = await send(_headers(token));
    if (response.statusCode == 401 && _accessTokenProvider != null) {
      token = await _resolveAccessToken(forceRefresh: true);
      response = await send(_headers(token));
    }
    return response;
  }

  Future<String> _resolveAccessToken({bool forceRefresh = false}) async {
    final provider = _accessTokenProvider;
    if (provider != null) return provider(forceRefresh: forceRefresh);
    return _accessToken!;
  }

  Map<String, dynamic> _data(http.Response response) {
    Object? decoded;
    try {
      decoded = jsonDecode(response.body);
    } catch (_) {
      decoded = null;
    }
    if (response.statusCode < 200 || response.statusCode >= 300) {
      final error = decoded is Map<String, dynamic> ? decoded['error'] : null;
      final message = error is Map<String, dynamic>
          ? error['message'] as String?
          : error as String?;
      throw MediaException(message ?? 'The upload could not be completed.');
    }
    if (decoded is! Map<String, dynamic>) {
      throw const MediaException('Media storage returned invalid data.');
    }
    final data = decoded['data'];
    if (data is! Map<String, dynamic>) {
      throw const MediaException('Media storage returned invalid data.');
    }
    return data;
  }
}

class MediaException implements Exception {
  const MediaException(this.message);

  final String message;

  @override
  String toString() => message;
}
